### ISSUE TITLE
Migration to v5 guide - missing getSession

### ISSUE THREAD

**Issue by mmarrius** [nextauthjs/next-auth#10941]
### What is the improvement or update you wish to see?

`Use auth() instead of getServerSession, getSession, withAuth, getToken, and useSession` is found [here](https://authjs.dev/getting-started/migrating-to-v5) but then `getSession` is nowhere else on the page described. Should `auth()` be used instead of it? If yes, why isn't it included in the list of examples?

### Is there any context that might help us understand?

`getSession` is the bread and butter in v4 but is sparsely mentioned in v5. Should it still be used?

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/migrating-to-v5

**Comment by ndom91** [comment]
Hey yeah so there's a hard split between where you should use `auth()` and where you shuold use `getSession`/`useSession`.

- `auth()` is the new "all-in-one" method that works everywhere **server-side** (i.e. in server components as well).
- Client-side, you can still use `getSession`/`useSession` as before. They're imported from `next-auth/react` and of course `useSession` still requires the components to be wrapped in the `SessionProvider`, right.

We recommend grabbing your session in the nearest server-component and passing it down via props to a client-component though, instead of using those client methods, if possible.

**Comment by ndom91** [comment]
If theres any specific improvements you'd like to see, feel free to open a PR and we can talk about it more there :pray: 

Otherwise, i'll close this issue for now

**Comment by tindl88** [comment]
I can't use `getSession` after upgrading from v4 to v5 beta 19

```
import { getCsrfToken, getSession, signOut } from 'next-auth/react';

const interceptors = {
  onRequest: async (config: InternalAxiosRequestConfig): Promise<InternalAxiosRequestConfig> => {
    const headers = config.headers;
    const session = await getSession();

    console.log('session', session);

    if (session) headers.Authorization = `Bearer ${session.accessToken}`;

    return config;
  }
  ...
 }
```
It raise the error: TypeError: (0 , next_auth_react__WEBPACK_IMPORTED_MODULE_0__.getSession) is not a function
