### ISSUE TITLE
next_auth_react__WEBPACK_IMPORTED_MODULE_0__.getServerSession

### ISSUE THREAD

**Issue by soukainakhalkhouli** [nextauthjs/next-auth#5187]
### Environment

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/71095703/185470361-6b29f600-6a3b-4a70-a33d-9707bd4bc9c1.png">

### Reproduction URL

"react": "^17.0.2", "react-dom": "^17.0.2",  "next": "^12.1.6",  "next-auth": "^4.10.3",

### Describe the issue

I'm trying to log in into our application after upgrading next-auth from v3 to v4 :
I've imported the getServerSession function as follows :
import { getServerSession } from "next-auth/react"

export async function addUserHeader(req, res) {

    const session = await getServerSession({ req });
    res.setHeader('X-Authenticated-User', String(session?.user?.email))
  }

And when i'm running application locally i'm getting TypeError: (0 , next_auth_react__WEBPACK_IMPORTED_MODULE_0__.getServerSession) is not a function. i'm using following versions of the packages
"react": "^17.0.2",
"react-dom": "^17.0.2",
 "next": "^12.1.6",
 "next-auth": "^4.10.3",

Can anyone let me know where the issue might be ? Thank you!

### How to reproduce

"react": "^17.0.2",
"react-dom": "^17.0.2",
 "next": "^12.1.6",
 "next-auth": "^4.10.3",

### Expected behavior

"react": "^17.0.2",
"react-dom": "^17.0.2",
 "next": "^12.1.6",
 "next-auth": "^4.10.3",

**Comment by rumon5h** [comment]
I got this problem on my next js project 

`Unhandled Runtime Error
TypeError: (0 , react_firebase_hooks_auth__WEBPACK_IMPORTED_MODULE_5__.useSignOut) is not a function or its return value is not iterable

Source
src\components\navbar\Navbar.jsx (15:49) @ auth
