### ISSUE TITLE
next-auth doesn't work on Netlify

### ISSUE THREAD

**Issue by Gustavo-Contreiras-Hotels-at-Home** [nextauthjs/next-auth#7717]
### Environment

In my machine it works.
I don't know Netlify environment.

### Reproduction URL

I can't share the repository. But it's working on local so the code is fine.

### Describe the issue

I can't access any route of next-auth in the production site.
If I try to access `https://bbbbbbbnnnnnnn.netlify.app/api/auth/session` I always get `Internal server error`

I already tried to follow https://next-auth.js.org/errors#client_fetch_error
And already tried to follow https://docs.netlify.com/integrations/frameworks/next-js/overview/#nextauth-js-support
Both didn't solve it.

It works perfectly in my machine but not in live site.

### How to reproduce

Not possible.

### Expected behavior

Return me my session data.

**Comment by oreoluwa-bs** [comment]
Having the same issue

**Comment by GustavoContreiras** [comment]
Hosting on Vercel worked

**Comment by oreoluwa-bs** [comment]
Thanks I fixed it by downgrading "@netlify/plugin-nextjs": "4.32.2". It's Netlify's runtime for Nextjs application

**Comment by ayebrian** [comment]
Jun 3, 09:55:00 PM: 7cbb56ba ERROR  Error: Cannot find module '/var/task/.next/server/pages/api/auth/[...nextauth].js'
Require stack:
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/.netlify/functions-internal/api-0/api-0.js
- /var/task/api-0.js
- /var/runtime/index.mjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at /var/task/node_modules/next/dist/server/require-hook.js:188:36
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at NetlifyNextServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:656:34)
    at NetlifyNextServer.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1187:21)
    at Object.fn (/var/task/node_modules/next/dist/server/next-server.js:1130:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:315:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/.netlify/functions-internal/api-0/api-0.js',
    '/var/task/api-0.js',
    '/var/runtime/index.mjs'
  ]
}

/api/auth/* doesn't work, also this is happening after upgrade NodeJS from 18.15.0 to 18.16.0
