### ISSUE TITLE
Type error in session callback for `user` and `token` properties

### ISSUE THREAD

**Issue by thomasmol** [nextauthjs/next-auth#9633]
### Environment

npmPackages:
@auth/core: ^0.* => 0.20.0
@auth/drizzle-adapter: ^0.* => 0.3.14
@auth/sveltekit: ^0.* => 0.5.2
Node: 20.3.1 - /opt/homebrew/bin/node

### Reproduction URL

https://github.com/thomasmol/authjsbugs

### Describe the issue

related to #9437

i get a type error in the session callback for the `user` or `token` property:
```
Property 'user' does not exist on type '({ session: Session; user: AdapterUser; } | { session: Session; token: JWT; }) & { newSession: any; trigger?: "update" | undefined; }'.
```

error claims `user` does not exist, while it does, although it depends on the database strategy used.

error located here on the `user` property in `hooks.server.ts`:
```typescript 
callbacks: {
  session: async ({ session, user }) => {
    if(session.user){
      session.user.id = user.id;
      }
    return session;
  }
},
```
not sure if useful but this is copilot explaining:
"The error message you're seeing is due to TypeScript not being able to determine the exact type of the object that's being passed to the session callback. The type of the object is a union type, which means it could be one of several types. In this case, it could be { session: Session; user: AdapterUser; } or { session: Session; token: JWT; }.

The user property exists on the first type, but not on the second. When you try to access user.id, TypeScript can't guarantee that user will always be present, hence the error."

### How to reproduce

install auth core + auth sveltekit, create hooks.server.ts and add a the session callback. type error occurs on user and token, but not the session property.

### Expected behavior

no type errors

**Comment by nbifrye** [comment]
This seems to be related to https://github.com/Microsoft/TypeScript/issues/14094.

Minimum code:

```typescript
type Obj1 = { a: string, b: string }
type Obj2 = { a: string, c: string }

const func = (args: Obj1 | Obj2) => {
    args.b = ""
         ^ Property 'b' does not exist on type 'Obj1 | Obj2'.
}
```

https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwIxQLxQN5QIYC4oDOwATgJYB2A5gDRRz5FlVQC+AUKJLIgExqY4GJCjSgBjIU0qs2bMQHtyRKADMAruTH8AFNmKUC+eMigAfbgh4BKNAD5MbKE5z6CAOjj8ARF7bsgA

Using `{ session, user?, token? }` instead of `{ session, user } | { session, token }` seems to fix this.

**Comment by Kinbaum** [comment]
Can confirm this on the latest `next-auth: 5.0.0-beta.5`
<img width="581" alt="Screenshot 2024-01-18 at 9 17 07 AM" src="https://github.com/nextauthjs/next-auth/assets/6590356/1ad4cde5-9230-4a34-9cb5-e3c92d7b8ae7">

**Comment by BernardinoOtais** [comment]
> Can confirm this on the latest `next-auth: 5.0.0-beta.5`
> 
> <img alt="Screenshot 2024-01-18 at 9 17 07 AM" width="581" src="https://private-user-images.githubusercontent.com/6590356/297768815-1ad4cde5-9230-4a34-9cb5-e3c92d7b8ae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTY4ODksIm5iZiI6MTcwNTU5NjU4OSwicGF0aCI6Ii82NTkwMzU2LzI5Nzc2ODgxNS0xYWQ0Y2RlNS05MjMwLTRhMzQtOWNiNS1lM2M5MmQ3YjhhZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMTY0OTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNlMzAwYWEyNDc4M2U4NDhhODI5NDNhNDVhMDcxMGUzMTkxZThjMDc4MzRjYmIyMTEyZTA3ZWY0MjYyOGVlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OChhrwg7LOjAA-ZJBqLWdls6SUFavBDWRB8eYhQ27So">

It's also happening to me...

**Comment by sahilq312** [comment]
> Can confirm this on the latest `next-auth: 5.0.0-beta.5`
> 
> <img alt="Screenshot 2024-01-18 at 9 17 07 AM" width="581" src="https://private-user-images.githubusercontent.com/6590356/297768815-1ad4cde5-9230-4a34-9cb5-e3c92d7b8ae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MDM0OTEsIm5iZiI6MTcwNTYwMzE5MSwicGF0aCI6Ii82NTkwMzU2LzI5Nzc2ODgxNS0xYWQ0Y2RlNS05MjMwLTRhMzQtOWNiNS1lM2M5MmQ3YjhhZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMTgzOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWYyNGIxODU3ZmZhYjRjNjE5NGI5MDhiYzNmNzRjNDg0M2E1YmU4MzQyYTIzZjc1NzdiMDk4ZDQxYTg5M2E0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1p_h4kqPj_eriA55EGHxWAAJOIK0D2J_xisoy7ThVlk">

i am also facing the same problem . did yu find any solution

**Comment by thomasmol** [comment]
i think #9646 is the solution to this as proposed by @nbifrye. It is more due to a limitation in typescript rather than authjs

**Comment by igmtink** [comment]
I have same problem

**Comment by jeremy-code** [comment]
FYI for a quick fix, just manually set the types while setting user as optional, e.g.

```javascript
import NextAuth, { type Session, type User } from "next-auth";

export const auth = NextAuth({
  callbacks: {
    async session({ session, user }: { session: Session; user?: User }) {
      if (user) {
        // do whatever here
      }
      return session;
    },
  },
});

```

**Comment by BernardinoOtais** [comment]
> FYI for a quick fix, just manually set the types while setting user as optional, e.g.
> 
> ```js
> import NextAuth, { type Session, type User } from "next-auth";
> 
> export const auth = NextAuth({
>   callbacks: {
>     async session({ session, user }: { session: Session; user?: User }) {
>       if (user) {
>         // do whatever here
>       }
>       return session;
>     },
>   },
> });
> ```

Taking in consideration what jeremy-code posted, this is how I did it:

import NextAuth, { Session, User } from "next-auth";

    async session(
      params:
        | { session: Session; user: User }
        | { session: Session; token: JWT },
    ) {
      if (!("token" in params)) return params.session;

      const sessao = {
        ...params.session,
        token: params.token,
      };
      return sessao;
    },
  }

**Comment by ypanagidis** [comment]
Same here, when trying to access the token in the session callback using the jwt strategy, it wont let me access the second part of the params which included the token. Only present in authjs 5 beta 5, not in authjs 5 beta 4.

**Comment by sahilq312** [comment]
> Same here, when trying to access the token in the session callback using the jwt strategy, it wont let me access the second part of the params which included the token. Only present in authjs 5 beta 5, not in authjs 5 beta 4.

`async session({ session, token}: {session: Session, token?: any}) {` 
 this is what worked for me you can also try  as far i understood this is a typescript error .

**Comment by ayinde-xyz** [comment]
I am also having the same error

**Comment by Ealanisln** [comment]
On my case I fix the first error (Property token does not exist on type session Session user) but now the token is not being recognized. 

<img width="671" alt="Screenshot 2024-01-21 at 4 24 47 PM" src="https://github.com/nextauthjs/next-auth/assets/87247953/5f3a4639-8714-46bf-be82-a16e7525d864">

**Comment by hellogbg** [comment]
My experience is that it works on 5.0.0-beta.4
but not on 5.0.0-beta.5

**Comment by Ealanisln** [comment]
I was able to pass the error putting '?' on the token. I'm in Next Auth Beta 5.

<img width="798" alt="Screenshot 2024-01-22 at 12 30 08 PM" src="https://github.com/nextauthjs/next-auth/assets/87247953/33e5cb9a-9cfb-4873-8080-50434f8acbc7">

**Comment by travistylervii** [comment]
Downgrading to beta.4 was the easiest and least hacky fix that worked for me. Make sure to delete the ^ symbol. 

Before:
![CleanShot 2024-01-23 at 22 26 04@2x](https://github.com/nextauthjs/next-auth/assets/4889865/06c0e8e1-b239-4984-9ea1-0c671ca00584)

After:
![CleanShot 2024-01-23 at 22 26 32@2x](https://github.com/nextauthjs/next-auth/assets/4889865/40745044-815d-4ab0-8833-2578e6996554)

**Comment by SamuelOliveira-M** [comment]
In my case I solved it as follows : 
`import { JWT } from "next-auth/jwt"
 
declare module "next-auth/jwt" {
  /** Returned by the `jwt` callback and `auth`, when using JWT sessions */
  interface JWT {
    /** OpenID ID Token */
    idToken?: string
  }
`
This way, there is no longer an error in the token parameter of the session object and I can even add more fields if I want within the token in addition to those that already come by default.
[https://authjs.dev/getting-started/typescript](url)
