### ISSUE TITLE
Can't login with Prisma Adapter on sqlite

### ISSUE THREAD

**Issue by eden6** [nextauthjs/next-auth#1166]
**Describe the bug**
I get a `[get_user_by_provider_account_id_error] TypeError: prisma[Account].findOne is not a function` on login with GitHub provider. I get the correct profile data in the console but the user is never created in the db.
I use the same schema file than the one on [Next-Auth Website](https://next-auth.js.org/schemas/adapters#prisma-schema).

I get that the error is related to database but migrations work.

Same GitHub secret and id work with the TypeORM adapter.

**Steps to reproduce**
Create a new NextJs project, install next-auth and follow the [Prisma Adapter tutorial](https://next-auth.js.org/schemas/adapters#prisma-adapter)

[Have a look at this repo](https://github.com/eden6/next-auth-login)

**Expected behavior**
Create a new user and session and not return a error

**Screenshots or error logs**
![error](https://user-images.githubusercontent.com/10814148/105230902-0e395f00-5b34-11eb-9af2-29db910983f3.png)

Thank you!

**Comment by simonedelmann** [comment]
I have the same error. This is because `findOne` was deprecated in Prisma 2.14 and removed in 2.15, which was released today. The 3.2.0@canary should already have a fix for this. (It will try that in a second...)

**Comment by balazsorban44** [comment]
@simonedelmann is right. #881 fixed this, and is available at the canary release.

**Comment by dalalRohit** [comment]
Yes, next-auth is not working with @prisma/cli-2.15.0 and @prisma/client-2.15.0

downgraded both to @2.14.0
