### ISSUE TITLE
`e.getSetCookie is not a function` using `next` v13.5.5

### ISSUE THREAD

**Issue by RaenonX** [nextauthjs/next-auth#8881]
### Environment

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 20.05 GB / 63.81 GB
  Binaries:
    Node: 18.12.1 - C:\SDKs\nodejs-18\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\SDKs\nodejs-18\npm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.46)
    Internet Explorer: 11.0.22621.1
```

### Reproduction URL

https://github.com/RaenonX/next-auth-13.5.5-repro

### Describe the issue

When the page loads, the error below will show for every render. Sign in page won't be able to load (unable to sign in).

![image](https://github.com/nextauthjs/next-auth/assets/18443743/b1cb6029-39cd-4fca-bd71-d27b6b4ce08f)

I didn't test the production build, but interestingly the production build of the project that's using `next` v13.5.5 and `next-auth` doesn't have this error (dev build still has this issue), users can sign in as well.

Confirmed that this won't happen if the `next` version is locked to `13.5.4`.

### How to reproduce

1. Clone the `next-auth-example` template repo
2. `yarn install` with the latest `next.js` (precisely v13.5.5)
3. `yarn dev`
4. See the error

### Expected behavior

No error printed in the console, able to get into the sign in page.

**Comment by kneza23** [comment]
Same thing is happening to me when updating to 13.5.5

**Comment by Brettkgamble** [comment]
Dev environment breaks at at next 13.5.5-canary.18.  Can confirm that production builds for releases greater than 13.5.5-canary.18 all work on vercel deployment.

**Comment by Brettkgamble** [comment]
Upgrade Node.js to 18.18.2 resolved the issue in dev.

**Comment by RaenonX** [comment]
> Upgrade Node.js to 18.18.2 resolved the issue in dev.

This works for me as well. However, `next` is now saying this, do you have the same error? Haven't got time to try to make a repro yet
![image](https://github.com/nextauthjs/next-auth/assets/18443743/a3879009-f35e-42d9-b60b-09115766efff)

**Comment by balazsorban44** [comment]
This is a bug in Next.js, not NextAuth.js. You can follow https://github.com/vercel/next.js/issues/56949 for updated. If you are using Node.js 18.16 though, you are not affected by this, so you can upgrade if that's possible.

@RaenonX for your case, you can follow https://github.com/vercel/next.js/issues/56919
