### ISSUE TITLE
Prisma Adapter 

### ISSUE THREAD

**Issue by anubisoft** [nextauthjs/next-auth#1987]
## Description 🐜
As of the 3.21.1 release, the Prisma adapter object now returns an 'undefined' value for it's 'Adapter' in previously working code that sets up the NextAuth configuration object. The following line from the Nextjs example project that sets up the configuration object is where the 'undefined' Adapter error now occurs:

adapter: Adapters.Prisma.Adapter({ prisma }),  

In adapters/prisma.js, I can see that the 'Adapter' export is:

`
Object.defineProperty(exports, "Adapter", {
  enumerable: true,
  get: function () {
    return _prismaLegacyAdapter.PrismaLegacyAdapter;  // I'm guessing this should be returning '.Adapter' instead
  }
});
`

**Comment by balazsorban44** [comment]
That is interesting, please fill out the whole bug report template, so we can help!

I have tried with both Webpack 4 and Webpack 5 locally and had no problems.

**Comment by wrod7** [comment]
`TypeError: next_auth_adapters__WEBPACK_IMPORTED_MODULE_1___default(...).Prisma.Adapter is not a function
    at Object../src/pages/api/auth/[...nextauth].ts (/home/wrod/dev/sticky/.next/server/pages/api/auth/[...nextauth].js:40:77)
    at __webpack_require__ (/home/wrod/dev/sticky/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/wrod/dev/sticky/.next/server/pages/api/auth/[...nextauth].js:153:52)
    at /home/wrod/dev/sticky/.next/server/pages/api/auth/[...nextauth].js:154:28
    at Object.<anonymous> (/home/wrod/dev/sticky/.next/server/pages/api/auth/[...nextauth].js:157:3)`

getting this error after upgrading to 3.21.1

**Comment by wrod7** [comment]
`TypeError: next_auth_adapters__WEBPACK_IMPORTED_MODULE_1___default(...).Prisma.Adapter is not a function at Object../src/pages/api/auth/[...nextauth].ts (.../.next/server/pages/api/auth/[...nextauth].js:40:77) at __webpack_require__ (.../.next/server/webpack-runtime.js:25:42) at __webpack_exec__ (.../.next/server/pages/api/auth/[...nextauth].js:153:52) at .../.next/server/pages/api/auth/[...nextauth].js:154:28 at Object.<anonymous> (.../.next/server/pages/api/auth/[...nextauth].js:157:3)`

getting this error after updating to 3.21.1

**Comment by balazsorban44** [comment]
Someone please provide a reproduction, otherwise we cannot help!

I used this repository https://github.com/nextauthjs/next-auth-example

and tested it with both Webpack 4 and Webpack 5, and had no problems!


Without sharing more information, I have no idea where to even begin. Please help us, so we can help you.

**Comment by wrod7** [comment]
@balazsorban44 I was able to resolve my error by removing "@types/next-auth" from my dev dependencies.

**Comment by balazsorban44** [comment]
@anubisoft unless you can provide a reproduction, I'm going to close this.

**Comment by anubisoft** [comment]
@balazsorban44 Investigating this today. I'll comment with what I discover, if anything. Unlike wrod7 I don't have "@types/next-auth" in my dependencies.

**Comment by anubisoft** [comment]
Noob mistake on my part. This error went away after I deleted my yarn.lock file. To prevent this type of error in the future I updated my project's install:clean step to delete the yarn.lock file now that I'm using yarn.

**Comment by balazsorban44** [comment]
happy that it worked out after all! 🎉😁

**Comment by zackdotcomputer** [comment]
I investigated this having run into it separately in #2008 - I documented what I found to be causing the issue [here](https://github.com/nextauthjs/next-auth/issues/2008#issuecomment-841797746) but tldr; is that because the dependency on the legacy adapter packages points to the version "canary" rather than a *specific* canary, the fact that `3.20.1` updated the which-canary dependency internally caused build breaks for people who both: 1) used a legacy adapter and 2) upgraded across the 3.20.0 to 3.20.1 boundary.

For us, the dependency graph *appeared* satisfied because we had a canary installed with canary-115, but it was in fact not satisfied because the `next-auth` code was configured for canary-127. This is why blowing away your yarn.lock fixed it - you forced the package manager to download the latest build that satisfied "canary". I'm not sure why removing `@types/next-auth` would also fix this issue other than that it might cause the package manager to redetermine dependencies because of the uninstall? Or perhaps you deleted `node_modules`?

(On a side note, @anubisoft I would recommend against regularly deleting your `yarn.lock` file - it will cause yarn to upgrade dependencies without your control and can create hard-to-debug headaches.)
