### ISSUE TITLE
Module Augmentation doesn't work since last update

### ISSUE THREAD

**Issue by davulrich** [nextauthjs/next-auth#5542]
### Question 💬

After upgrade next-auth from 4.12.2 to 4.13.0. Type augmentation doesn't work as expected regarding the docs.

In [...nextauth].ts in signIn callback function, user type is now:

```typescript
user: User | {
  email: string;
};
 ```
When I want access user in my current signIn callback implementation, TS shows me error bellow:
```TS error: Property 'id' does not exist on type 'User | { email: string; }'.```

I didn't found any info regarding this change. I would like to avoid to create helper function which check if user parameter is User type. I also tried to typecast the parameter but with it brings more errors...

Can you check please if it's a bug or expected behaviour which is not covered yet in docs and I need to check the type by myself now?

### How to reproduce ☕️

```typescript
async signIn({user}) {
      const userISID = user.id.toUpperCase()
      // rest of the code
 }
 ```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by alex289** [comment]
Same here, I tried everything

**Comment by magicspon** [comment]
Snap

**Comment by ThangHuuVu** [comment]
Thanks for the catch, we recently had a big TS refactor #4953, so probably this bug is its unfortunate result. Will have a look ASAP 🙌

**Comment by kachar** [comment]
I can report a similar scenario by using `authorize` callback with v4.13.0.

We provide a jwt and refresh token when the user gets authenticated and this return type is no longer supported.

```tsx
async authorize(credentials) {
  return {
    jwtToken: '....',
    refreshToken: '....',
  }
}
```

```
Type '{ jwtToken: any; refreshToken: string; }' is not assignable to type 'Omit<User, "id"> | { id?: string | undefined; } | null'.ts(2322)
```

**Comment by enricoros** [comment]
There seem to be 2 issues here, one is changing the TS signature of callbacks, which breaks existing source code, and another where module augmentation is broken as well.

As mentioned, `async signIn({ user: User, account...` became `async signIn({ user: User | {email: string}, account...`, which breaks compilation. Is this callback supposed to return either type? 

Then, the other issue is not being able to add custom properties anymore. Need to roll back to 4.12.3?

**Comment by mbazanowski-merixstudio** [comment]
As a temporary workaround (because i had to deploy my update right now) i've added `as User` this to make typescript satisfied:
```ts
 callbacks: {
    async signIn({
      user, account,
    }) {
      // TODO: Remove (as User) after https://github.com/nextauthjs/next-auth/issues/5542 is fixed
      const idToken = ((user as User).id_token || account?.id_token) as string;
```

Not best solution, but it works with current latest next-auth version (4.13.0)

**Comment by ThangHuuVu** [comment]
Thanks everyone for jumping in, this should be fixed now, will do a release soon 🙌
