### ISSUE TITLE
next-auth not working with Prisma 2.15

### ISSUE THREAD

**Issue by m-abdelwahab** [nextauthjs/next-auth#1169]
The latest [release](https://github.com/prisma/prisma/releases/tag/2.15.0) of Prisma (version 2.15) introduced a breaking change where the `findOne` method got removed. 

```
[next-auth][error][get_session_error] TypeError: prisma[Session].findOne is not a function
    at /Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/adapters/prisma/index.js:317:49
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/adapters/prisma/index.js:16:103)
    at _next (/Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/adapters/prisma/index.js:18:194)
    at /Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/adapters/prisma/index.js:18:364
    at new Promise (<anonymous>)
    at /Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/adapters/prisma/index.js:18:97
    at _getSession (/Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/adapters/prisma/index.js:339:28)
    at getSession (/Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/adapters/prisma/index.js:309:28)
    at /Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/server/routes/session.js:92:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/server/routes/session.js:22:103)
    at _next (/Users/m-abdelwahab/Desktop/hidden-gems/node_modules/next-auth/dist/server/routes/session.js:24:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 

```

To fix this issue, `findUnique` should be used instead of `findOne` in the Prisma adapter

**Comment by balazsorban44** [comment]
This is fixed on the `next-auth@canary` release:
https://github.com/nextauthjs/next-auth/issues/1166#issuecomment-764026546
