### ISSUE TITLE
Versions beyond 3.13.2 are triggering an issue with getInitialProps on credentials pages

### ISSUE THREAD

**Issue by jaxomlotus** [nextauthjs/next-auth#1852]
**Describe the bug**
After updating from 3.13.2 to the latest version (I think 3.16.2 introduced the problem and it persists in 3.17.2) my credentials pages no longer recognize providers() and csrfToken as functions passed in from the import. Instead it shows TypeError: Object(...) is not a function errors. 
- Note that this only happens when visiting the page directly in the browser - eg. https://mywebsite.com/auth/signin or https://mywebsite.com/auth/register
- When using the {signIn} function directly, there is no issue.

**Steps to reproduce**
Steps to reproduce the behavior.

- Update to the latest version of nextauth. 
- Visit a credentials page directly via URL.

I don't have a link to a repository as my project isn't public, but following the above steps should work. Otherwise I can give an admin access to my project, if needed.

**Expected behavior**
There should be no errors - getInitialProps should recognize providers() and csrfToken exactly as passed in.

**Screenshots or error logs**
If applicable add screenshots or error logs to help explain the problem.

`[POST] /api/auth/_log
12:27:25:34
2021-04-25T16:27:25.734Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module './cjs/react-dom-server.node.development.js'\nRequire stack:\n- /var/task/node_modules/react-dom/server.node.js\n- /var/task/node_modules/react-dom/server.js\n- /var/task/node_modules/next/dist/next-server/server/render.js\n- /var/task/node_modules/next/dist/next-server/server/next-server.js\n- /var/task/___next_launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module './cjs/react-dom-server.node.development.js'","Require stack:","- /var/task/node_modules/react-dom/server.node.js","- /var/task/node_modules/react-dom/server.js","- /var/task/node_modules/next/dist/next-server/server/render.js","- /var/task/node_modules/next/dist/next-server/server/next-server.js","- /var/task/___next_launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1063:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)","    at Module.load (internal/modules/cjs/loader.js:928:32)","    at Function.Module._load (internal/modules/cjs/loader.js:769:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)","    at internal/main/run_main_module.js:17:47"]}
Unknown application error occurred
Runtime.ImportModuleError`

**Additional context**
I wish I knew what was triggering this issue so I could be helpful to you all, but unfortunately I have no context here. The only thing that fixed this issue was reverting back to 3.13.2

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
I might have an idea, could you please cheeck if `getCsrfToken` and `getProviders` work? (they should be aliases for the functions you seem to have issues with.

I think the problem was this PR https://github.com/nextauthjs/next-auth/pull/1791

It seemingly started causing problems. I thought that Webpack4 will simply ignore `exports`, but somehow it doesn't.

If you know how and have the opportunity, could you see if enabling Webpack 5 in your Next.js config works?

**Comment by jaxomlotus** [comment]
Thanks for the fast reply. Enabling webpack5 is now triggering this error:

Server Error
TypeError: (0 , next_auth_client__WEBPACK_IMPORTED_MODULE_2__.providers) is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Complete log below:
`TypeError: (0 , next_auth_client__WEBPACK_IMPORTED_MODULE_2__.providers) is not a function
    at Function.exports.modules../pages/auth/[credentials].tsx.SignIn.getInitialProps (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\.next\server\pages\auth\[credentials].js:4624:81)
    at loadGetInitialProps (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\lib\utils.js:5:101)
    at loadGetInitialProps (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\lib\utils.js:5:24)
    at renderToHTML (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\render.js:28:1529)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\next-server.js:112:97
    at async C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\next-server.js:105:142
    at async DevServer.renderToHTMLWithComponents (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\next-server.js:137:387)
    at async DevServer.renderToHTML (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\next-server.js:138:923)
    at async DevServer.renderToHTML (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\server\next-dev-server.js:35:578)
    at async DevServer.render (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\next-server.js:75:236)
    at async Object.fn (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\next-server.js:59:580)
    at async Router.execute (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\router.js:25:67)
    at async DevServer.run (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\next-server.js:69:1042)
    at async DevServer.handleRequest (C:\Users\muchn\OneDrive\Documents\GitHub\burnerpage\burnerpage-admin-2\node_modules\next\dist\next-server\server\next-server.js:34:504)`

**Comment by jaxomlotus** [comment]
No, unfortunately this didn't help. I'm now getting the following error across the board. 

[POST] /api/auth/_log
15:04:41:51
2021-04-25T19:04:42.078Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module './cjs/react-dom-server.node.development.js'\nRequire stack:\n- /var/task/node_modules/react-dom/server.node.js\n- /var/task/node_modules/react-dom/server.js\n- /var/task/node_modules/next/dist/next-server/server/render.js\n- /var/task/node_modules/next/dist/next-server/server/next-server.js\n- /var/task/___next_launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module './cjs/react-dom-server.node.development.js'","Require stack:","- /var/task/node_modules/react-dom/server.node.js","- /var/task/node_modules/react-dom/server.js","- /var/task/node_modules/next/dist/next-server/server/render.js","- /var/task/node_modules/next/dist/next-server/server/next-server.js","- /var/task/___next_launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1063:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)","    at Module.load (internal/modules/cjs/loader.js:928:32)","    at Function.Module._load (internal/modules/cjs/loader.js:769:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)","    at internal/main/run_main_module.js:17:47"]}
Unknown application error occurred
Runtime.ImportModuleError

Strangely enough, this only happens on Vercel - not locally. So I am honestly at a loss as to what could be going on.

**Comment by balazsorban44** [comment]
So if you create a local build and try running it with `next start` it works, but not when it is built/deployed on Vercel?

**Comment by jaxomlotus** [comment]
> So if you create a local build and try running it with `next start` it works, but not when it is built/deployed on Vercel?

Well I am running it locally with "yarn dev" I haven't figured out how to set up SSL locally to work with next yet.

**Comment by balazsorban44** [comment]
`yarn dev` is not the same as how you run it in Vercel, you would need a production build. So if you run `next build` and then `yarn start`, it should start a local production version on `http://localhost:3000`. I'm not sure about SSL? but just for the sake of seeing if the problem still appears.

Also, could you maybe add a reproduction repo or similar? I actually don't see anything directly `next-auth` related

**Comment by jaxomlotus** [comment]
OK, I was able to get it running locally with Yarn start.

I'll try to set up a reproduction repo for you - if it's OK with you, I'll add you to it directly.

**Comment by jaxomlotus** [comment]
Actually, it looks like it's fixed. So two things solved this:

1) Your idea that using aliases with webpack was causing the issue. After removing another alias that I had setup on Provider, it's fixed.
2) I had a flag set to development instead of production. This was preventing your fix from working properly on vercel. By fixing that all is good now (I hope - will continue to test...).

Thanks again for your help!

**Comment by balazsorban44** [comment]
That's awesome! Feel free to report back, and close this issue when you verified that it has actually been resolved!

**Comment by jaxomlotus** [comment]
Yes - looks like this did indeed solve my issue so I will close this. Thank you again! 

Just to reiterate for anyone else who runs into this problem: If you import any Nextauth functions using aliases and run into issues where webpack no longer recognizes them, just remove them and things should work again...
